### PR TITLE
adds frame prop to manually control current frame of animation

### PR DESCRIPTION
**Pull request by ProPanek**
We needed to make animation controllable in our project. This simple change can allow everyone to manipulate and control current frame of animation using Props.

### CODE REVIEW

**Comment by jcblw** [comment]
interesting what is the use case? Also before we merge this we will need a test for this functionality.

**Comment by ProPanek** [comment]
We needed to change the frames of our animation depending on the position of the scroll. And by testing you mean `jest` test or just example of usage?

**Comment by jcblw** [comment]
Ok awesome! That's a cool use case. A jest test 🙏

**Comment by jcblw** [comment]
Thank you! Looks great

**Comment by jcblw** [comment]
published@1.2.0

**Pull request merged**
