### PR TITLE
Fix for onEnd callback + documentation

### PR DESCRIPTION
**Pull request by htopia**
Fixed an issue where onEnd was getting triggered on start.
Added onEnd to the Readme documentation.

### CODE REVIEW

**Comment by htopia** [comment]
@jcblw Here it is, not sure if I did this right, this is my first time collaborating into another project.

**Comment by jcblw** [comment]
You can just copy paste the code if you want

**Comment by htopia** [comment]
> You can just copy paste the code if you want

Actually I think it's already there, I used your branch as the base.

**Comment by jcblw** [comment]
@htopia sorry you are correct, switched the base branch to master. Thanks again.

**Comment by jcblw** [comment]
@htopia changes published in `react-sprite-animator@2.0.1`

**Comment by htopia** [comment]
yay! thanks @jcblw!

**Pull request merged**
