### PR TITLE
useSprite was missing frame prop implementation

### PR DESCRIPTION
**Pull request by buzzin0609**
Noticed the frame prop wasn't working, so added this little snippet so users can set the current frame using the prop

### CODE REVIEW

**Review by jcblw — APPROVED** [review]
Nice catch this looks great! Sorry, it took so long to see this.

**Comment by jcblw** [comment]
@buzzin0609 looks like it's missing the formatting rules of the repo. I can fix it up this weekend, but if you can get to it before then it would be much appreciated :D

**Comment by jcblw** [comment]
fixed in #247

**Comment by buzzin0609** [comment]
@jcblw sorry I also missed your replies here. Great that it's merged in 👍

**Pull request closed without merging**
